apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pantry--io-ingress
spec:
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pantry-io
                port:
                  number: 80
  tls:
    - hosts:
        - api.example.com
      secretName: pantry-tls-secret